services:
  ignition:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.tag-cicd.entrypoints: "web"
      traefik.http.routers.tag-cicd.rule: "Host(`tag-cicd.localtest.me`)"
      traefik.http.services.tag-cicd.loadbalancer.server.port: "8088"
    environment:
      GATEWAY_SYSTEM_NAME: tag-cicd
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: tag-cicd.localtest.me
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy