services:
  gateway:
    image: bwdesigngroup/ignition-docker:8.1.43
    environment:
      GATEWAY_MODULES_ENABLED: perspective
      ADDITIONAL_DATA_FOLDERS: tags
      DEVELOPER_MODE: Y
    volumes:
      - ../build/Tag-CICD.modl:/usr/local/bin/ignition/user-lib/modules/Tag-CICD.modl
      - ./backups/gateway.gwbk:/restore.gwbk
      - ./temp/ignition-data:/workdir
    labels:
      traefik.enable: "true"
      traefik.hostname: "tag-cicd"
    command: >
      -n tag-cicd
      -r /restore.gwbk
    networks:
      - default
      - proxy
    
networks:
  default:
  proxy:
    external: true
    name: proxy