name: Build Module and Upload to Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        java-package: jdk
        java-version: 11
    - 
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    - 
      name: Unpack Keystore and Cert
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" >> release.keystore.asc;
        gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch release.keystore.asc > release.keystore;
        echo "${{ secrets.CERT_FILE_TEXT }}" > cert.crt;
    - 
      name: Build Module
      run: |
        ./gradlew build signModule --keystoreFile=release.keystore --keystorePassword="${{ secrets.KEYSTORE_PASSWORD }}"  --certFile=cert.crt --certPassword="${{ secrets.CERT_PASSWORD }}" --certAlias="${{ secrets.CERT_ALIAS }}"
    - 
      name: Upload to Release Action
      uses: Shopify/upload-to-release@v1.0.1
      with:
        name: 'Tag-CICD.modl'
        path: 'build/Tag-CICD.modl'
        repo-token: ${{ secrets.GITHUB_TOKEN }}