name: Build PRs
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'
      - name: Build
        run: ./gradlew build
      - name: Upload Unsigned Module
        uses: actions/upload-artifact@v3
        with:
          name: tag-cicd-unsigned
          path: build/Tag-CICD.unsigned.modl