name: Publish new version upon tag commit
on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and release'
        required: true

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'
      - name: Deserialize signing certs
        run: |
          echo "${{ secrets.CODE_SIGNING_CERT_BASE64 }}" | base64 --decode > cert.crt
          echo "${{ secrets.CODE_SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks
      - name: Build & create signed module
        run: >
          ./gradlew
          -Pversion=${{ github.event.inputs.tag || github.ref_name }}
          -PsignModule=true
          build
          signModule 
          --certFile=cert.crt
          --certPassword="${{ secrets.CODE_SIGNING_CERT_PASSWORD }}"
          --keystoreFile=keystore.jks
          --keystorePassword="${{ secrets.CODE_SIGNING_KEYSTORE_PASSWORD }}"
          --certAlias="${{ secrets.CODE_SIGNING_CERT_ALIAS }}"
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.event.inputs.tag || github.ref_name }}
          prerelease: false
          files: |
            build/Tag-CICD.modl
            LICENSE.txt